### ISSUE TITLE
How can I find the csv files?

### ISSUE THREAD

**Issue by ElijahMingLiu** [dawei-liang/Audioset_research#1]
Hi! I am a student majoring in computer science. You guys did a very excellent work, and I very appreciate your paper! But when I run your code on my own computer it seems that I can't find the csv files.
- **replacement_data_15classes.csv**  
-  **replacement_labels_15classes.csv** 
-  **feasibility_overall_0726.csv** 
- **SMOTE_data_15classes.csv**
- **SMOTE_labels_15classes.csv**

 Can you please provide me with these files, please? 
My e-mail is qqliuming1995@gmail.com
Thanks a lot!

**Comment by dawei-liang** [comment]
Hi, sorry I just noticed your inquiry. Thanks for your interest!

The _replacement_data_15classes.csv_ and _SMOTE_data_15classes.csv_ can be generated using the _main_resample.py_ script in the github. They are resampled datasets following the over-sampling steps in our paper. The script needs to take as input raw Audioset embeddings in csv format.

The _feasibility_overall_0726.csv_ is our feasibility dataset. Unfortunately, we cannot share it to the public due to privacy protection. You can collect it on your own following the same way as described in our paper.

Please let me know if you have any issues. Sorry for the late reply. Thanks!
